// @ts-nocheck
// These JSON files are generated by scripts/preprocess.ts
// Using dynamic imports with Vite's static asset handling
import postalLookupData from './postalLookup.json';
import districtsJsonData from './districts.json';

export const postalLookup = postalLookupData as Record<string, { bydel: string; lokaludvalg: string }>;
export const districtsData = districtsJsonData as {
  bydel: Record<string, any>;
  lokaludvalg: Record<string, any>;
  subDistrict: Record<string, any>;
};
